### ISSUE TITLE
glitch enemies?

### ISSUE THREAD

**Issue by JonathanSteininger** [EvaisaDev/noita.fairmod#303]
I can't tell if the enemies in this screenshot are meant to be like a glitch or if it really is a glitch.

shooting firebug shots

![image](https://github.com/user-attachments/assets/577285f2-f3db-43d8-b0c3-157011b2f12f)

**Comment by heinermann** [comment]
That's intentional. They are glitched enemies, just like the glitched spells.

**Comment by JonathanSteininger** [comment]
Thanks, just a bit hard to tell with such a chaotic mod lol.
